# include sla oq
if __name__ == '__main__':
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
    print('deu certo 3')
